M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date ned 12 mar 2023 22:42:52
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-12T22:42:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.090
%
G90
G05
T1
X648.97Y-213.995
X648.97Y-224.155
T0
M30
